---
title: Supplementary Table 1
output: bookdown::html_document2
editor_options:
  chunk_output_type: console
---

<style type="text/css">
.main-container {
  max-height:  3000px;
  margin-top:    auto;
  margin-bottom: auto;
  max-width:   3000px;
  margin-left:   auto;
  margin-right:  auto
}
</style>

```{r setup, include=FALSE}
# Environment setup:
gc()

# Libraries:
library(knitr)

# Constants:
DOC_DIR      <- getwd()
ROOT_DIR     <- "../.."
SRC_DIR      <- "src"
SRC_FILEPATH <- file.path(SRC_DIR, "Analyses.R")

# Knitr configuration:
opts_knit$set(root.dir = ROOT_DIR) # Interferes with officedown!
opts_chunk$set(
  echo    = FALSE,
  results = 'hide',
  message = FALSE,
  warning = FALSE,
  cache   = TRUE,
  autodep = TRUE
)
```

```{r load-chunks, cache=FALSE}
SRC_FILEPATH |> read_chunk()
```

```{r includes, cache=FALSE}
```

```{r load-data}
```

```{r country-derivate-vars}
```

```{r health-topic-derivate-vars}
```

```{r analyses-derivate-vars}
```

```{r create-output-dataset}
```

```{r create-headers-labels}
```

```{r initiatives-table-supplementary, cache=FALSE}
```

```{r initiatives-table-supplementary-output, results='asis', cache=FALSE}
supplementary_table_output
```

Main information of the initiatives included in the mapping.  
*Note:*
`r countries_footnote`.  
Empty cells represent non-available information.
