---
title: |
  Worldwide mapping of initiatives that integrate population cohorts
output:
  officedown::rdocx_document:
    base_format:     bookdown::word_document2
    reference_docx:  ../../www/Epidemiology_title_page_template.docx
    number_sections: no
    page_size:
      width:         8.5
      height:       11
    page_margins:
      bottom:        1
      top:           1
      right:         1
      left:          1
      gutter:        0
---

**Type of manuscript:** Systematic review

## Author's full names and affiliations:

Laura Alejandra Rico-Uribe^1,2,†^;
Daniel Morillo-Cuadrado^1,3,†^;
Ángel Rodríguez-Laso^4^;
Ellen Vorstenbosch^1,5,6^;
Andreas J. Weser^7^;
Laura Fincias^5^;
Yannick Marcon^8^;
Leocadio Rodriguez-Mañas^4^;
Josep María Haro^5,6^;
José Luis Ayuso-Mateos^1,3,9^

<br>

^1^ CIBERSAM (Network-based Biomedical Research Consortium,
    area of Mental Health), Instituto de Salud Carlos III,
    Spanish Ministry of Science and Innovation.

^2^ School of Health Sciences, Universidad Internacional de La Rioja

^3^ Instituto de Investigación Sanitaria La Princesa (IIS-LP),
    Hospital Universitario de La Princesa, Madrid, Spain

^4^ CIBERFES (Network-based Biomedical Research Consortium,
    area of Frailty and Healthy Ageing), Instituto de Salud Carlos III,
    Spanish Ministry of Science and Innovation.

^5^ Parc Sanitari Sant Joan de Déu, Barcelona, Spain

^6^ Universitat de Barcelona, Barcelona, Spain

^7^ HUNT Research Centre, Norwegian University of Science and Technology,
    Levanger, Norway

^8^ Epigeny, St. Ouen, France

^9^ Department of Psychiatry, Universidad Autónoma de Madrid, Madrid, Spain

<br>

^†^ Joint first authors

## Corresponding author:

Daniel Morillo-Cuadrado  
Universidad Autónoma de Madrid, Department of Psychiatry.
Arzobispo Morcillo 4, 28029 Madrid, Spain.  
Phone nº: +34 914975816  
E-mail: daniel.morillo@cibersam.es

<br>

**Running head suggestion:** Initiatives that integrate population cohorts

## Conflicts of interest

None declared.

## Sources of funding

The results reported herein correspond to specific aims of grant
825884 to the Syncrhros Consortium from the European Union’s Horizon 2020
research and innovation programme.
LARU's and DM's work was supported by the
Network-based Biomedical Research Consortium,
area of Mental Health (CIBERSAM), Instituto de Salud Carlos III,
Spanish Ministry of Science and Innovation.

## Data and computing code availability

All the data and computing code required to replicate these results can be
accessed at  
https://github.com/CCOMS-UAM/mapping-initiatives
